<?php
global $testsConfiguration;
$testsConfiguration = new \DrdPlus\Tests\RulesSkeleton\TestsConfiguration('http://pribeh.bestiar.drdplus.loc', 'https://pribeh.bestiar.drdplus.info');
$testsConfiguration->disableHasLinksToJournals();
$testsConfiguration->disableHasLinkToSingleJournal();
$testsConfiguration->disableHasTables();
$testsConfiguration->disableHasNotes();
$testsConfiguration->disableHasProtectedAccess();
$testsConfiguration->disableHasCustomBodyContent();
$testsConfiguration->disableHasAuthors();
$testsConfiguration->disableHasDebugContacts();
$testsConfiguration->disableHasCharacterSheet();
$testsConfiguration->disableCanBeBoughtOnEshop();
$testsConfiguration->setBlockNamesToExpectedContent([]);
$testsConfiguration->setExpectedWebName('Příběh z DrD+ bestiáře');
$testsConfiguration->setExpectedPageTitle('⛏️ Příběh z DrD+ bestiáře');
$testsConfiguration->disableHasLinksToAltar();
$testsConfiguration->disableHasMoreVersions();
$testsConfiguration->disableHasExternalAnchorsWithHashes();
$testsConfiguration->setExpectedGoogleAnalyticsId('UA-121206931-13');
$testsConfiguration->setExpectedLastVersion('master');